"""ACT phase — create GitHub issues or draft PRs for identified gaps."""

import logging

from src.apis.github_client import GitHubClient
from src.models import ActionType, GapAnalysis

logger = logging.getLogger(__name__)

LABEL = "chaos-coordinator"


def build_issue_body(gap: GapAnalysis, agent_name: str) -> str:
    """Build a GitHub issue body from a gap analysis."""
    lines = []
    lines.append(f"## Chaos Test Coverage Gap")
    lines.append("")
    lines.append(f"**Bug:** [{gap.bug.key}]({gap.bug.url})")
    lines.append(f"**Component:** {gap.bug.component}")
    lines.append(f"**Priority:** {gap.bug.priority}")
    lines.append(f"**Confidence:** {gap.confidence_level.value} ({gap.confidence_score}/100)")
    lines.append("")
    lines.append(f"### Bug Summary")
    lines.append("")
    lines.append(gap.bug.summary)
    lines.append("")
    lines.append(f"### Gap Analysis")
    lines.append("")
    lines.append(gap.reasoning)
    lines.append("")

    if gap.base_scenario:
        lines.append(f"### Suggested Approach")
        lines.append("")
        lines.append(f"**Base scenario to extend:** `{gap.base_scenario}`")
        lines.append("")
        if gap.modifications:
            lines.append("**Modifications:**")
            for mod in gap.modifications:
                lines.append(f"- {mod}")
            lines.append("")

    lines.append("### Action Required")
    lines.append("")
    if gap.action_type == ActionType.DRAFT_PR:
        lines.append("This gap has **high confidence** — a draft PR with scenario changes is recommended.")
    else:
        lines.append("This gap needs **human review** to determine the best approach.")
    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by krkn-chaos-coordinator / {agent_name} agent*")

    return "\n".join(lines)


def build_issue_title(gap: GapAnalysis) -> str:
    """Build a GitHub issue title from a gap analysis."""
    level = gap.confidence_level.value.upper()
    summary = gap.bug.summary[:80]
    return f"[chaos-coordinator] [{level}] {gap.bug.key}: {summary}"


def create_issues_for_gaps(
    github: GitHubClient,
    gaps: list[GapAnalysis],
    agent_name: str,
    owner: str = "krkn-chaos",
    repo: str = "krkn",
    dry_run: bool = True,
) -> list[dict]:
    """Create GitHub issues for each gap.

    Args:
        github: GitHub API client
        gaps: List of gap analyses to create issues for
        agent_name: Name of the agent that found the gaps
        owner: GitHub repo owner
        repo: GitHub repo name
        dry_run: If True, print what would be created without creating

    Returns:
        List of created issue dicts (or dry run previews)
    """
    results = []

    for gap in gaps:
        title = build_issue_title(gap)
        body = build_issue_body(gap, agent_name)

        if dry_run:
            logger.info("DRY RUN — would create issue:")
            logger.info("  Title: %s", title)
            logger.info("  Repo: %s/%s", owner, repo)
            results.append({
                "dry_run": True,
                "title": title,
                "body": body,
                "bug_key": gap.bug.key,
                "confidence": gap.confidence_level.value,
            })
            print(f"\n{'='*60}")
            print(f"ISSUE PREVIEW: {title}")
            print(f"{'='*60}")
            print(body)
            print(f"{'='*60}\n")
        else:
            result = github.create_issue(
                owner=owner,
                repo=repo,
                title=title,
                body=body,
                labels=[LABEL],
            )
            if result:
                logger.info("Created issue: %s", result.get("html_url"))
                results.append(result)
            else:
                logger.error("Failed to create issue for %s", gap.bug.key)

    return results
